name: Test PX4-Sim-Gazebo Homebrew Formula

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test-formula:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup local tap for formula testing
        run: |
          brew update
          brew tap-new px4/px4
          mkdir -p "$(brew --repo px4/px4)/Formula"
          cp Formula/px4-sim-gazebo.rb "$(brew --repo px4/px4)/Formula/"

      - name: "Debug: list tapped formulae"
        run: |
          echo "Formulas in tap:"
          ls -R "$(brew --repo px4/px4)/Formula"

      - name: "Debug: tap info"
        run: |
          brew tap-info px4/px4

      - name: Install formula from local tap
        run: |
          brew install --build-from-source px4/px4/px4-sim-gazebo

      - name: Test formula
        run: |
          brew test px4/px4/px4-sim-gazebo

      - name: Audit formula
        run: |
          brew audit --strict --online px4/px4/px4-sim-gazebo
