name: Build and Test PX4 Homebrew Formulas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Building ${{ matrix.formula }}
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        formula:
          - px4-dev
          - px4-sim-gazebo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Homebrew
        run: brew update

      - name: Tap PX4/px4 repository
        run: brew tap px4/px4 "${{ github.workspace }}"

      - name: Install formula
        run: brew install --build-from-source ${{ matrix.formula }}

      - name: Install Python dependencies
        if: ${{ matrix.formula == 'px4-dev' }}
        run: |
          python3 -m pip install pyserial

      - name: Verify installation
        run: brew list --versions ${{ matrix.formula }}

      - name: Run formula tests
        run: brew test ${{ matrix.formula }}

      - name: Audit formula
        run: brew audit --strict --online Formula/${{ matrix.formula }}.rb
