name: Build, Test & Compile PX4 Projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Building ${{ matrix.formula }}
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - formula: px4-dev
            build_target: px4_fmu-v5
          - formula: px4-sim-gazebo
            build_target: px4_sitl_default

    steps:
      - name: Checkout Homebrew tap
        uses: actions/checkout@v4
        with:
          repository: px4/homebrew-px4
          path: homebrew-px4

      - name: Update Homebrew
        run: brew update

      - name: Tap PX4/px4 repository
        working-directory: homebrew-px4
        run: brew tap px4/px4 "${{ github.workspace }}/homebrew-px4"

      - name: Checkout PX4 Autopilot
        uses: actions/checkout@v4
        with:
          repository: PX4/PX4-Autopilot
          path: px4-autopilot
          fetch-depth: 0

      - name: Install PX4 Python dependencies
        working-directory: px4-autopilot
        uses: py-actions/py-dependency-install@v1
        with:
          requirements-path: Tools/setup/requirements.txt
          python-version: 3.11

      - name: Install formula
        run: brew install --build-from-source ${{ matrix.formula }}

      - name: Run formula tests
        run: brew test ${{ matrix.formula }}

      - name: Audit formula
        run: brew audit --strict --online "homebrew-px4/Formula/${{ matrix.formula }}.rb"

      - name: Build PX4 Autopilot
        working-directory: px4-autopilot
        run: make ${{ matrix.build_target }}