name: Build and Test PX4 Homebrew Formulas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Building px4-dev
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Homebrew
        run: brew update

      - name: Create local tap for all formulas
        run: |
          brew tap-new px4/local
          mkdir -p "$(brew --repo px4/local)/Formula"
          cp Formula/*.rb "$(brew --repo px4/local)/Formula/"

      - name: Build and test px4-dev formula
        run: |
          brew install --build-from-source px4/local/px4-dev
          brew list --versions px4-dev
          brew test px4-dev
          brew audit --strict --online px4/local/px4-dev

      - name: Build and test px4-sim-gazebo formula
        run: |
          brew install --build-from-source px4/local/px4-sim-gazebo
          brew list --versions px4-sim-gazebo
          brew test px4-sim-gazebo
          brew audit --strict --online px4/local/px4-sim-gazebo
