name: Mac OS Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    env:
      HOMEBREW_DEVELOPER: "1"
    steps:
    - name: Tap PX4
      run: brew tap PX4/px4
    - name: Install PX4 Dev
      run: brew install px4-dev
    - name: Install Python dependencies
      run: pip3 install --user --upgrade pyserial empy toml pandas jinja2 packaging pyyaml pyros-genmsg
    - name: Run PX4 test build
      run: git clone -b master https://github.com/PX4/Firmware.git ~/Firmware && cd ~/Firmware && make px4_fmu-v5x_default
    - name: Test PX4 Sim environment
      run: brew install px4-sim
