name: Build and Test PX4 Homebrew Formulas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-px4-dev:
    name: Building px4-dev
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Homebrew
        run: brew update

      - name: Tap PX4/px4 repository
        run: brew tap px4/px4 "${{ github.workspace }}"

      - name: Install and test px4-dev
        run: |
          brew install --build-from-source px4-dev
          brew list --versions px4-dev
          brew test px4-dev
          brew audit --strict --online Formula/px4-dev.rb

  build-px4-sim-gazebo:
    name: Building px4-sim-gazebo
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Homebrew
        run: brew update

      - name: Tap PX4/px4 repository
        run: brew tap px4/px4 "${{ github.workspace }}"

      - name: Install and test px4-sim-gazebo
        run: |
          brew install --build-from-source px4-sim-gazebo
          brew list --versions px4-sim-gazebo
          brew test px4-sim-gazebo
          brew audit --strict --online Formula/px4-sim-gazebo.rb
